########### DATABASE CONNECTION CONFIGURATION ###################
database : mysql
max_connection : 5
max_idle_connection : 5
db_username : root
db_password :
db_name : omdb_log
db_host : 127.0.0.1
db_port : 3306

